# Generated by Django 2.2.5 on 2019-09-24 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='foto_carregada',
            field=models.ImageField(upload_to='media'),
        ),
    ]
